pipeline{
	agent any
	tools{
		mvn "MAVEN3"
		jdk "OracleJDK8"
	}
	environment{
		NEXUS_LOGIN = 'nexuslogin'
		NEXUSIP = '172.31.27.32' // Nexus EC2 Private IP
		NEXUSPORT = '8081'
		NEXUS-USER = 'admin'
		NEXUS-PASS = 'admin'
		CENTRAL-REPO = 'vpro-maven-central'
		RELEASE-REPO = 'vprofile-release'
		SNAP-REPO = 'vprofile-snapshot'
		NEXUS-GRP-REPO = 'vpro-maven-group'
	}
	stages{
		stage('Build'){
			steps{
				sh 'mvn -s setting.xml -DskipTests install'
			}
		}
	}
}