Parameters:
  NameOfService:
    Description: Name of the service the stack used to
    Type: String
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  KeyName:
    Description: Name of EC2 Login Key
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  AMIRegionMap:
    us-east-2:
      AMI: ami-088b41ffb0933423f
    us-east-1:
      AMI: ami-085ad6ae776d8f09c

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - AMIRegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      SubnetId: subnet-065578495c7890b9c
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
      MetaData:
        AWS::CloudFormation::Init:
          config:
            packages:
              yum:
                php: []
                httpd: []
                wget: []
                unzip: []
                git: []
            commands:
              test:
                command: "wget https://www.tooplate.com/zip-templates/2121_wave_cafe.zip && unzip 2121_wave_cafe.zip && cp -r 2121_wave_cafe/* /var/www/html/"
            files:
              /var/www/html/hello.html:
                content: !Sub
                  <!DOCTYPE html>
                  <html>
                  <body>
                    <h1>Welcome to CloudFormation</h1>
                    <p>this site is deployed by CloudFormation</p>
                  </body>
                  </html>
            services:
              sysvinit:
                httpd:
                  enabled: true
                  ensureRunning: true
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
    
Outputs:
  PrintSomeInfo:
    Value: !GetAtt
      - MyInstance
      - PublicDnsName