Mappings:
  AMIRegionMap:
    us-east-2:
      AMI: ami-088b41ffb0933423f
    us-east-1:
      AMI: ami-085ad6ae776d8f09c

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - AMIRegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: t2.micro
      SubnetId: subnet-065578495c7890b9c
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, first, instance]]
    