AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPS3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: vpr-cicd-data-s3
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: vps3fullaccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:s3:::*'
  VPSInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    InstanceProfileName: vpr-cicd-data-s3
    Properties:
      Path: /
      Roles:
        - !Ref VPS3Role

Outputs:
  VPs3RoleDetails:
    Description: VP CICD Role S3 info
    Value: !Ref VPSInstanceProfile
    Export:
      Name: cicds3role-VPS3RoleProfileName