pipeline{
	agent any
	tools{
		maven "MAVEN3"
		jdk "OracleJDK8"
	}
	environment{
		NEXUS_LOGIN = 'nexuslogin'
		NEXUSIP = '172.31.27.32' // Nexus EC2 Private IP
		NEXUSPORT = '8081'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'admin'
		CENTRAL_REPO = 'vpro-maven-central'
		RELEASE_REPO = 'vprofile-release'
		SNAP_REPO = 'vprofile-snapshot'
		NEXUS_GRP_REPO = 'vpro-maven-group'
	}
	stages{
		stage('Build'){
			steps{
				dir('P7-Continuous-Integration-using-Jenkins-Sonarqube-Nexus-Slack/vprofile-project-ci-jenkins'){
					sh 'mvn -s settings.xml -DskipTests install'
				}
			}
		}
	}
}