- name: Set Hosts to IP Mapping in /etc/hosts file for all servers 
  hosts: all
  tasks:
    - name: Import VPC steup variable file
      include_vars: 
        file: group_vars/hostsip

    - name: Update host files for all the host  
      blockinfile: 
        path: /etc/hosts
        block: |
          {{ web01_ip }} web01
          {{ app01_ip }} app01
          {{ mc01_ip }} mc01
          {{ rmq01_ip }} rmq01
          {{ db01_ip }} db01