- name: Build Artifact ROOT.war and SQL file to be copied in files/directory
  import_playbook: build.yml

- name: Set Hosts to IP Mapping in /etc/hosts file for all servers 
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on  dbserver
  import_playbook: dbdeploy.yml

- name: Setup Memcached Service
  import_playbook: memcache.yml

- name: Setup RabitMQ Service
  import_playbook: rabbitmq.yml

- name: Setup Tomcat Application server
  import_playbook: appserver.yml

- name: Setup Nginx webserver
  import_playbook: web.yml